# This is a basic workflow to help you get started with Actions

name: Daily update

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'data/**'
  pull_request:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 3 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install gdal
      run: |
        sudo apt-get install gdal-bin
        ogr2ogr --version

    - name: Cache EGP downloads
      uses: actions/cache@v1
      env:
        cache-name: cache-egp-downloads
      with:
        path: data/downloaded/
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}
          ${{ runner.os }}-build-
          ${{ runner.os }}-


    # Runs a single command using the runners shell
    - name: Run make
      env:
        username: ${{ secrets.egpUsername }}
        password: ${{ secrets.egpPassword }}
      run: locale && make

    # Runs a set of commands using the runners shell
    - name: Check git diff
      run: |
        ls -lah data/downloaded/
        ls -lah data/
        git status
        git diff --stat
        git diff data/SR.csv

    # Git commit + push, see https://github.com/github-actions-x/commit
    - name: Publish changes to git
      if: github.ref == 'refs/heads/master'
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'Data update 🤖'
        files: data/
        name: GURS RPE update bot
